### PR TITLE
Amber conversion update

### PR DESCRIPTION
**Pull request by jchodera**
This PR is to debug AMBER conversion issues.

Currently, we're seeing:
```
Traceback (most recent call last):
  File "convert_amber.py", line 990, in <module>
    main()
  File "convert_amber.py", line 90, in main
    convert_yaml(args.input, ffxml_dir='ffxml/')
  File "convert_amber.py", line 386, in convert_yaml
    standard_ffxml=standard_ffxml)
  File "convert_amber.py", line 825, in validate_water_ion
    ff = app.ForceField(ffxml_name, standard_ffxml)
  File "/Users/choderaj/miniconda3/lib/python3.5/site-packages/simtk/openmm/app/forcefield.py", line 178, in __init__
    self.loadFile(files)
  File "/Users/choderaj/miniconda3/lib/python3.5/site-packages/simtk/openmm/app/forcefield.py", line 286, in loadFile
    self.registerResidueTemplate(template)
  File "/Users/choderaj/miniconda3/lib/python3.5/site-packages/simtk/openmm/app/forcefield.py", line 411, in registerResidueTemplate
    raise ValueError('Residue template %s with the same override level %d already exists.' % (template.name, template.overrideLevel))
ValueError: Residue template AL with the same override level 0 already exists.
```

### CODE REVIEW

**Comment by jchodera** [comment]
Looks like the problem is with `ffxml/tip3p_HFE_multivalent.xml`:
```
Water and ions energy validation for ffxml/tip3p_HFE_multivalent.xml
Preparing temporary files for validation...
Preparing LeaP scripts...
Running LEaP...
Calculating and validating energies...
Deleting temp files...
Traceback (most recent call last):
  File "convert_amber.py", line 987, in <module>
    main()
  File "convert_amber.py", line 90, in main
    convert_yaml(args.input, ffxml_dir='ffxml/')
  File "convert_amber.py", line 390, in convert_yaml
    standard_ffxml=standard_ffxml)
  File "convert_amber.py", line 824, in validate_water_ion
    ff = app.ForceField(ffxml_name, standard_ffxml)
  File "/home/travis/miniconda3/envs/test/lib/python3.5/site-packages/simtk/openmm/app/forcefield.py", line 178, in __init__
    self.loadFile(files)
  File "/home/travis/miniconda3/envs/test/lib/python3.5/site-packages/simtk/openmm/app/forcefield.py", line 286, in loadFile
    self.registerResidueTemplate(template)
  File "/home/travis/miniconda3/envs/test/lib/python3.5/site-packages/simtk/openmm/app/forcefield.py", line 411, in registerResidueTemplate
    raise ValueError('Residue template %s with the same override level %d already exists.' % (template.name, template.overrideLevel))
ValueError: Residue template AL with the same override level 0 already exists.
```

**Comment by jchodera** [comment]
I think the issue is that `tip3p_HFE_multivalent` contains `tip3p_standard`, and that both include `lib/atomic_ions.lib`:
```yaml
- Source:
  - parm/frcmod.ions234lm_hfe_tip3p
  - lib/atomic_ions.lib
  Standard: tip3p_standard
  Solvent: tip3p
  Name: tip3p_HFE_multivalent
```
and
```yaml
- Source:
  - parm/frcmod.ionsjc_tip3p
  - parm/frcmod.ions234lm_126_tip3p
  - lib/atomic_ions.lib
  Solvent_source: tip3p.xml
  Solvent: tip3p
  Name: tip3p_standard
```
Do we need a `tip3p.xml` that omits the ions if we're going to include them in `tip3p_HFE_multivalent`?

**Comment by jchodera** [comment]
Now we're back to issues with impropers:
```
lski1962:amber choderaj$ python convert_amber.py 
Traceback (most recent call last):
  File "convert_amber.py", line 987, in <module>
    main()
  File "convert_amber.py", line 90, in main
    convert_yaml(args.input, ffxml_dir='ffxml/')
  File "convert_amber.py", line 377, in convert_yaml
    validate_rna(ffxml_name, leaprc_name)
  File "convert_amber.py", line 693, in validate_rna
    system_name='nucleic-RNA')
  File "convert_amber.py", line 450, in assert_energies
    (system_name, i[0], i[1], improper_tolerance, ffxml))
AssertionError: nucleic-RNA energies (PeriodicTorsionForce-impropers, 0.189635) outside of allowed tolerance (0.010000) for ffxml/ff14SB.redq.xml
```

**Comment by jchodera** [comment]
I should note that `travis` and I are both using the new AmberTools 17, which you can install with:
```bash
conda install --yes -c http://ambermd.org/downloads/ambertools/conda/ ambertools
```

**Comment by rafwiewiora** [comment]
Should be fixed now.

**Comment by rafwiewiora** [comment]
I've added missing references in `master.yaml` and added one more RNA FF. This is all good to go now as far as I'm concerned.

**Comment by jchodera** [comment]
@rafwiewiora : Travis seems to be failing with a [unicode error](https://travis-ci.org/choderalab/openmm-forcefields/jobs/283432366#L1082-L1098) for python 2.7:
```
Converting /Users/travis/miniconda3/envs/test/bin/../dat/leap/cmd/leaprc.DNA.OL15 to ffxml...
Preprocessing the leaprc for DNA.OL15...
Converting to ffxml ffxml/DNA.OL15.xml...
Traceback (most recent call last):
  File "convert_amber.py", line 987, in <module>
    main()
  File "convert_amber.py", line 90, in main
    convert_yaml(args.input, ffxml_dir='ffxml/')
  File "convert_amber.py", line 364, in convert_yaml
    filter_warnings=filter_warnings, split_filename=True)
  File "convert_amber.py", line 195, in convert_leaprc
    params.write(ffxml_name, provenance=provenance, write_unused=write_unused, improper_dihedrals_ordering='amber')
  File "/Users/travis/miniconda3/envs/test/lib/python2.7/site-packages/parmed/openmm/parameters.py", line 229, in write
    self._write_omm_provenance(dest, provenance)
  File "/Users/travis/miniconda3/envs/test/lib/python2.7/site-packages/parmed/openmm/parameters.py", line 366, in _write_omm_provenance
    dest.write('  <%s>%s</%s>\n' % (tag, escaped_sub_content, tag))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u0301' in position 21: ordinal not in range(128)
```
I'll check if we have to address this or if we can get by with dropping python 2.7 support.

**Comment by jchodera** [comment]
Looks like that issue was due to an acute accent in an author name:
```YAML
- Source: leaprc.DNA.OL15
  Reference:
  - >-
    Zgarbová, M.; Sponer, J.; Otyepka, M.; Cheatham, T.E. III; Galindo-Murillo, R.; Jurecka, P. 
    Refinement of the Sugar-Phosphate Backbone Torsion Beta for AMBER Force Fields Improves the Description of Z- and B-DNA. 
    J. Chem. Theor. and Comp., 2015, 12, 5723–5736.
  Test:
  - dna
```
We'll punt on this for now but fix that later.

**Comment by rafwiewiora** [comment]
Aha - I've seen this many times before, but I always got an error - now I didn't, but it looks like it's okay on Python 3 but not on Python 2 so that's why. I just always deleted the accents if this happened.

**Pull request merged**
