### PR TITLE
Updating to AmberTools 18

### PR DESCRIPTION
**Pull request by jchodera**
This PR updates our Amber conversion to use [AmberTools 18 installed via conda](http://ambermd.org/GetAmber.php#ambertools).

### CODE REVIEW

**Comment by jchodera** [comment]
I am running into this error converting `leaprc.ff10`:
```
Converting /Users/choderaj/miniconda/bin/../dat/leap/cmd/oldff/leaprc.ff10 to ffxml...
Preprocessing the leaprc for ff10...
Converting to ffxml ffxml/ff10.xml...
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+54.ge824d26c-py3.6-macosx-10.9-x86_64.egg/parmed/amber/offlib.py:240: AmberWarning: Unexpected childsequence (3); expected 2 for residue SEP
  'residue %s' % (n, nres+1, name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+54.ge824d26c-py3.6-macosx-10.9-x86_64.egg/parmed/amber/offlib.py:240: AmberWarning: Unexpected childsequence (3); expected 2 for residue H2D
  'residue %s' % (n, nres+1, name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+54.ge824d26c-py3.6-macosx-10.9-x86_64.egg/parmed/amber/offlib.py:240: AmberWarning: Unexpected childsequence (3); expected 2 for residue S1P
  'residue %s' % (n, nres+1, name), AmberWarning)
Traceback (most recent call last):
  File "convert_amber.py", line 1214, in <module>
    main()
  File "convert_amber.py", line 105, in main
    convert_yaml(args.input, ffxml_dir='ffxml/')
  File "convert_amber.py", line 381, in convert_yaml
    filter_warnings=filter_warnings, split_filename=True)
  File "convert_amber.py", line 205, in convert_leaprc
    params = parmed.amber.AmberParameterSet.from_leaprc(leaprc)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+54.ge824d26c-py3.6-macosx-10.9-x86_64.egg/parmed/amber/parameters.py", line 298, in from_leaprc
    params.residues.update(AmberOFFLibrary.parse(_find_amber_file(fname, search_oldff)))
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+54.ge824d26c-py3.6-macosx-10.9-x86_64.egg/parmed/amber/offlib.py", line 138, in parse
    raise RuntimeError('Expected atoms table not found')
RuntimeError: Expected atoms table not found
```
cc: https://github.com/pandegroup/openmm/issues/2158

**Comment by rafwiewiora** [comment]
See my answer in https://github.com/ParmEd/ParmEd/issues/1003

**Comment by jchodera** [comment]
The atoms table issue has now been resolved, but we're now running into this issue:
```
Converting ['/Users/choderaj/miniconda/bin/../dat/leap/parm/frcmod.ionsjc_tip3p', '/Users/choderaj/miniconda/bin/../dat/leap/parm/frcmod.ions234lm_126_tip3p', '/Users/choderaj/miniconda/bin/../dat/leap/lib/atomic_ions.lib'] to ffxml...
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+63.gc3226b8c-py3.6-macosx-10.9-x86_64.egg/parmed/openmm/parameters.py:122: UserWarning: Residue AG contains atom type Ag+ not found in parameter set and will be dropped.
  warnings.warn('Residue {} contains atom type {} not found in parameter set and will be dropped.'.format(residue.name, atom.type))
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+63.gc3226b8c-py3.6-macosx-10.9-x86_64.egg/parmed/openmm/parameters.py:122: UserWarning: Residue CU1 contains atom type Cu+ not found in parameter set and will be dropped.
  warnings.warn('Residue {} contains atom type {} not found in parameter set and will be dropped.'.format(residue.name, atom.type))
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+63.gc3226b8c-py3.6-macosx-10.9-x86_64.egg/parmed/openmm/parameters.py:122: UserWarning: Residue H3O+ contains atom type H3O+ not found in parameter set and will be dropped.
  warnings.warn('Residue {} contains atom type {} not found in parameter set and will be dropped.'.format(residue.name, atom.type))
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+63.gc3226b8c-py3.6-macosx-10.9-x86_64.egg/parmed/openmm/parameters.py:122: UserWarning: Residue HE+ contains atom type HE+ not found in parameter set and will be dropped.
  warnings.warn('Residue {} contains atom type {} not found in parameter set and will be dropped.'.format(residue.name, atom.type))
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+63.gc3226b8c-py3.6-macosx-10.9-x86_64.egg/parmed/openmm/parameters.py:122: UserWarning: Residue HZ+ contains atom type HZ+ not found in parameter set and will be dropped.
  warnings.warn('Residue {} contains atom type {} not found in parameter set and will be dropped.'.format(residue.name, atom.type))
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+63.gc3226b8c-py3.6-macosx-10.9-x86_64.egg/parmed/openmm/parameters.py:122: UserWarning: Residue NH4 contains atom type NH4+ not found in parameter set and will be dropped.
  warnings.warn('Residue {} contains atom type {} not found in parameter set and will be dropped.'.format(residue.name, atom.type))
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-3.0.3+63.gc3226b8c-py3.6-macosx-10.9-x86_64.egg/parmed/openmm/parameters.py:122: UserWarning: Residue TL contains atom type Tl+ not found in parameter set and will be dropped.
  warnings.warn('Residue {} contains atom type {} not found in parameter set and will be dropped.'.format(residue.name, atom.type))
Modifying converted ffxml to append solvent parameters
ffxml/tip3p_standard.xml successfully written!
Validating the conversion...
Water and ions energy validation for ffxml/tip3p_standard.xml
Preparing temporary files for validation...
Preparing LeaP scripts...
Running LEaP...
Calculating and validating energies...
Deleting temp files...
Traceback (most recent call last):
  File "convert_amber.py", line 1214, in <module>
    main()
  File "convert_amber.py", line 105, in main
    convert_yaml(args.input, ffxml_dir='ffxml/')
  File "convert_amber.py", line 416, in convert_yaml
    standard_ffxml=standard_ffxml)
  File "convert_amber.py", line 990, in validate_water_ion
    system_omm = ff.createSystem(pdb.topology)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 1109, in createSystem
    [template, matches] = self._getResidueTemplateMatches(res, bondedToAtom, ignoreExternalBonds=ignoreExternalBonds)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 885, in _getResidueTemplateMatches
    raise Exception('Multiple matching templates found for residue %d (%s): %s.' % (res.index+1, res.name, ', '.join(match[0].name for match in allMatches)))
Exception: Multiple matching templates found for residue 8 (NA): NA, Na+.
```
This is occurring because I updated the [template hasher](https://github.com/ParmEd/ParmEd/blob/master/parmed/openmm/parameters.py#L456-L464) and accidentally included atom names (which OpenMM ignores while matching) in the hash. Once I correct this, the duplicate residue templates should be filtered out.

**Comment by jchodera** [comment]
This is just a reminder that I have to add the `CYS` patch manually in the tests.

**Comment by jchodera** [comment]
Looks like we'll need to add a way to manually specify CHARMM patches to retain to make more progress.

**Pull request merged**
