### PR TITLE
Integrate lipid merging prior to lipid validation in AMBER conversion script

### PR DESCRIPTION
**Pull request by jchodera**
This addresses https://github.com/choderalab/openmm-forcefields/issues/24 by integrating @peastman's lipid merging script to automatically convert lipid residues (overwriting the ffxml file) prior to energy validation tests.

To run this, simply run the AMBER conversion script from `amber/`:
```bash
python convert_amber.py --verbose
```

### CODE REVIEW

**Comment by jchodera** [comment]
@peastman: This is currently failing with
```
Converting to ffxml ffxml/lipid17.xml...
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-2.7.3+283.g4f6eb417.dirty-py3.6-macosx-10.7-x86_64.egg/parmed/amber/offlib.py:363: AmberWarning: residue table predicted 57, not 50 atoms for residue AR
  name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-2.7.3+283.g4f6eb417.dirty-py3.6-macosx-10.7-x86_64.egg/parmed/amber/offlib.py:363: AmberWarning: residue table predicted 59, not 52 atoms for residue DHA
  name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-2.7.3+283.g4f6eb417.dirty-py3.6-macosx-10.7-x86_64.egg/parmed/amber/offlib.py:363: AmberWarning: residue table predicted 57, not 50 atoms for residue OL
  name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-2.7.3+283.g4f6eb417.dirty-py3.6-macosx-10.7-x86_64.egg/parmed/amber/offlib.py:363: AmberWarning: residue table predicted 53, not 46 atoms for residue PA
  name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-2.7.3+283.g4f6eb417.dirty-py3.6-macosx-10.7-x86_64.egg/parmed/amber/offlib.py:363: AmberWarning: residue table predicted 46, not 38 atoms for residue PC
  name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-2.7.3+283.g4f6eb417.dirty-py3.6-macosx-10.7-x86_64.egg/parmed/amber/offlib.py:363: AmberWarning: residue table predicted 37, not 29 atoms for residue PE
  name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-2.7.3+283.g4f6eb417.dirty-py3.6-macosx-10.7-x86_64.egg/parmed/amber/offlib.py:363: AmberWarning: residue table predicted 39, not 31 atoms for residue PGR
  name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-2.7.3+283.g4f6eb417.dirty-py3.6-macosx-10.7-x86_64.egg/parmed/amber/offlib.py:363: AmberWarning: residue table predicted 28, not 20 atoms for residue PH-
  name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-2.7.3+283.g4f6eb417.dirty-py3.6-macosx-10.7-x86_64.egg/parmed/amber/offlib.py:363: AmberWarning: residue table predicted 39, not 31 atoms for residue PS
  name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-2.7.3+283.g4f6eb417.dirty-py3.6-macosx-10.7-x86_64.egg/parmed/amber/offlib.py:363: AmberWarning: residue table predicted 53, not 52 atoms for residue ST
  name), AmberWarning)
ffxml/lipid17.xml successfully written!
Merging lipid entries...
Validating the conversion...
Lipids (merged) energy validation for ffxml/lipid17.xml
Preparing temporary files for validation...
Preparing LeaP scripts...
Running LEaP...
Calculating and validating lipids energies...
Deleting temp files...
Traceback (most recent call last):
  File "convert_amber.py", line 1203, in <module>
    main()
  File "convert_amber.py", line 104, in main
    convert_yaml(args.input, ffxml_dir='ffxml/')
  File "convert_amber.py", line 425, in convert_yaml
    validate_merged_lipids(ffxml_name, leaprc_name)
  File "convert_amber.py", line 1176, in validate_merged_lipids
    system_name='lipids', topology=pdbfile.topology)
  File "convert_amber.py", line 561, in assert_energies
    system_omm = ff.createSystem(topology)
  File "/Users/choderaj/miniconda/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 1123, in createSystem
    raise ValueError('No template found for residue %d (%s).  %s' % (res.index+1, res.name, _findMatchErrors(self, res)))
ValueError: No template found for residue 1 (DOPC).  The set of atoms matches DOPC, but the bonds are different.  Perhaps the chain is missing a terminal group?
```
The relevant code is [here](https://github.com/choderalab/openmm-forcefields/pull/52/files#diff-60850f65ea5c62cdfb363b34095ee70aR431), and the test input file (just DOPC lipids in vacuum) is available in [CHARMM](https://github.com/choderalab/openmm-forcefields/blob/amber/amber/files/lipids_charmm.pdb) and [AMBER](https://github.com/choderalab/openmm-forcefields/blob/amber/amber/files/lipids_amber.pdb) formats.

I had to add to your script to also make sure to remove the residual CHARMM `<AllowPatches/>` tags, but I'm not sure why the AMBER and CHARMM bonds would be different for the same residues.

**Comment by peastman** [comment]
Your PDB file has no CONECT records.  That's why it doesn't know what the bonds are.

It also seems to have some other problems.  For example, residue names are only three characters, not four.  That file describes a set of DOP residues which are all on chain C, which is clearly not what was intended.

**Comment by jchodera** [comment]
Good catch! The POPC source files came from http://ambermd.org/tutorials/advanced/tutorial16/#Lipid_Bilayer_Structures, where they were generated by CHARMM-GUI. We used `step5_assembly.pdb` as the source for `lipids_charmm.pdb` and `DOPC_128.pdb` as the source for `lipids.pdb`.

If CHARMM-GUI does not produce PDB-compliant files, I'm not actually sure how to generate any valid lipid-containing files in both CHARMM and AMBER formats. Any ideas?

**Comment by peastman** [comment]
As part of implementing the membrane builder, I wrote a script that can add CONECT records for POPC and POPE lipids.  I'll mail it to you.

**Comment by jchodera** [comment]
Could you also post some demo boxes for POPC/POPE if you have them?

**Comment by peastman** [comment]
Here are files containing the membrane patches for them:

https://raw.githubusercontent.com/peastman/openmm/membrane/wrappers/python/simtk/openmm/app/data/POPC.pdb
https://raw.githubusercontent.com/peastman/openmm/membrane/wrappers/python/simtk/openmm/app/data/POPE.pdb

**Comment by jchodera** [comment]
Thanks!

I'm looking at the POPC.pdb file, but I'm confused by these atom types (and [AMBER](http://ambermd.org/tutorials/advanced/tutorial16/#Lipid_Bilayer_Structures) is too):
```
HETATM   65 0C21 POP A   1      42.000  10.850  39.360  1.00  0.00           C  
HETATM   66 1H10 POP A   1      41.860  11.900  39.050  1.00  0.00           H  
HETATM   67 1C21 POP A   1      42.540   9.980  38.260  1.00  0.00           C  
HETATM   68 H11R POP A   1      42.740   8.960  38.670  1.00  0.00           H  
HETATM   69 H11S POP A   1      43.590  10.240  38.010  1.00  0.00           H  
HETATM   70 2C21 POP A   1      41.650   9.700  37.050  1.00  0.00           C  
```

**Comment by jchodera** [comment]
@peastman : I was unable to convert POPE.pdb to [AMBER format](http://ambermd.org/tutorials/advanced/tutorial16/#Lipid_Bilayer_Structures). The AMBER conversion tool first doesn't understand your residue names, and even if they are modified to match, it doesn't understand your atom names to convert from CHARMM to AMBER.

I'm back working on this on Friday, so anything you can do to tackle the open issues before then would be super helpful. (You have write access to this repo.)

**Comment by peastman** [comment]
The atom names are the ones used in the files at http://www.fos.su.se/~sasha/SLipids/Downloads.html.  As far as I can tell, PDB doesn't define any standard names for lipids.  If they do, I haven't been able to locate them.  There are very few structures in the PDB that contain any lipids, and those seem to define their own names with HETNAM.

I believe VMD can also add CONECT records to PDB files, inferring bonds based simply on geometry, so that could be another solution.

**Comment by jchodera** [comment]
Go for it!

**Comment by peastman** [comment]
No, looks like VMD leaves out CONECT records too.  Sigh...

**Comment by jchodera** [comment]
@peastman : I've incorporated [your CHARMM-format `{POPC,POPE}.pdb` files](https://github.com/pandegroup/openmm/issues/1611#issuecomment-345833083) (and their AMBER conversions) into the testing after merging of lipid residues, but this currently fails with
```
lski2414:amber choderaj$ python convert_amber.py --verbose --input files/lipids-only.yaml
Converting /Users/choderaj/miniconda/bin/../dat/leap/cmd/leaprc.lipid17 to ffxml...
Preprocessing the leaprc for lipid17...
Converting to ffxml ffxml/lipid17.xml...
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-2.7.3+283.g4f6eb417.dirty-py3.6-macosx-10.7-x86_64.egg/parmed/amber/offlib.py:363: AmberWarning: residue table predicted 57, not 50 atoms for residue AR
  name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-2.7.3+283.g4f6eb417.dirty-py3.6-macosx-10.7-x86_64.egg/parmed/amber/offlib.py:363: AmberWarning: residue table predicted 59, not 52 atoms for residue DHA
  name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-2.7.3+283.g4f6eb417.dirty-py3.6-macosx-10.7-x86_64.egg/parmed/amber/offlib.py:363: AmberWarning: residue table predicted 57, not 50 atoms for residue OL
  name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-2.7.3+283.g4f6eb417.dirty-py3.6-macosx-10.7-x86_64.egg/parmed/amber/offlib.py:363: AmberWarning: residue table predicted 53, not 46 atoms for residue PA
  name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-2.7.3+283.g4f6eb417.dirty-py3.6-macosx-10.7-x86_64.egg/parmed/amber/offlib.py:363: AmberWarning: residue table predicted 46, not 38 atoms for residue PC
  name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-2.7.3+283.g4f6eb417.dirty-py3.6-macosx-10.7-x86_64.egg/parmed/amber/offlib.py:363: AmberWarning: residue table predicted 37, not 29 atoms for residue PE
  name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-2.7.3+283.g4f6eb417.dirty-py3.6-macosx-10.7-x86_64.egg/parmed/amber/offlib.py:363: AmberWarning: residue table predicted 39, not 31 atoms for residue PGR
  name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-2.7.3+283.g4f6eb417.dirty-py3.6-macosx-10.7-x86_64.egg/parmed/amber/offlib.py:363: AmberWarning: residue table predicted 28, not 20 atoms for residue PH-
  name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-2.7.3+283.g4f6eb417.dirty-py3.6-macosx-10.7-x86_64.egg/parmed/amber/offlib.py:363: AmberWarning: residue table predicted 39, not 31 atoms for residue PS
  name), AmberWarning)
/Users/choderaj/miniconda/lib/python3.6/site-packages/ParmEd-2.7.3+283.g4f6eb417.dirty-py3.6-macosx-10.7-x86_64.egg/parmed/amber/offlib.py:363: AmberWarning: residue table predicted 53, not 52 atoms for residue ST
  name), AmberWarning)
ffxml/lipid17.xml successfully written!
Merging lipid entries...
Validating the conversion...
Lipids (merged) energy validation for ffxml/lipid17.xml
Preparing temporary files for validation...
Preparing LeaP scripts...
Running LEaP...
Calculating and validating lipids energies...
Deleting temp files...
Traceback (most recent call last):
  File "convert_amber.py", line 1206, in <module>
    main()
  File "convert_amber.py", line 104, in main
    convert_yaml(args.input, ffxml_dir='ffxml/')
  File "convert_amber.py", line 425, in convert_yaml
    validate_merged_lipids(ffxml_name, leaprc_name)
  File "convert_amber.py", line 1179, in validate_merged_lipids
    system_name='lipids', topology=pdbfile.topology)
  File "convert_amber.py", line 592, in assert_energies
    (system_name, i[0], i[1], tolerance, ffxml, amber_energy, openmm_energy))
AssertionError: lipids relative energy error (HarmonicBondForce, 8889.055562) outside of allowed tolerance (0.000010) for ffxml/lipid17.xml: AMBER ('HarmonicBondForce', 5988.36572265625) OpenMM ('HarmonicBondForce', 53236904.0)
```
Is there a chance that some terms from the original CHARMM residues are accidentally being retained?

The incorporated lipid residue merging code is [here](https://github.com/choderalab/openmm-forcefields/pull/52/files#diff-60850f65ea5c62cdfb363b34095ee70aR431).

**Comment by peastman** [comment]
> Is there a chance that some terms from the original CHARMM residues are accidentally being retained?

I don't understand what you mean by that.  They're just PDB files.  If you aren't including any CHARMM force fields, there's no way you'll get any CHARMM energy terms.

**Comment by jchodera** [comment]
Apologies for not being hyper-explicit here.

Your [code](https://github.com/choderalab/openmm-forcefields/pull/52/files#diff-60850f65ea5c62cdfb363b34095ee70aR431) iterates through the CHARMM versions of residues and copies some information from the AMBER residue definitions it is merging into them. The modified CHARMM residue is returned as the newly merged AMBER residue. I was merely inquiring if this process may have accidentally neglected to replace some additional information, as the version you had sent me originally neglected to prune the CHARMM patches from the residue (though I already fixed that).

**Comment by peastman** [comment]
I can't think of anything else that could have gotten copied.  To have a huge harmonic bond energy like that, one of a few things must be happening:

1. Bonds are being included between atoms that shouldn't be bonded (seems unlikely, since the force field and the PDB file both have to agree about what's bonded).
2. Some atom positions are messed up.
3. Bond parameters are messed up.

**Comment by jchodera** [comment]
If I recall correctly, commenting out the parameter merging on [this line](https://github.com/choderalab/openmm-forcefields/pull/52/files#diff-60850f65ea5c62cdfb363b34095ee70aR389) and using [`validate_lipids`](https://github.com/choderalab/openmm-forcefields/pull/52/files#diff-60850f65ea5c62cdfb363b34095ee70aR424) instead of `validate_merged_lipids` (which just uses the AMBER versions of the same PDB file you gave me) works just fine, which excludes hypothesis 2.

I don't believe the parameter definitions are even being modified by `merge_lipids`, so I doubt hypothesis 3 is the case.

That leaves hypothesis 1?

**Comment by peastman** [comment]
It should be easy enough to check.  To start with, just compare the total number of bonds in each system to see if they're the same.  Assuming they are, loop over all of them and compare the two systems to see if the bonds are between the same atoms, and if they have the same parameters.

**Comment by jchodera** [comment]
Great---I can tackle that tomorrow.

**Comment by jchodera** [comment]
OK, a few of the residue templates have bond number mismatches:
```
CHARMM residue (DLPC) has 105 bonds; AMBER residues ({'PC', 'LAL'}) have 71 bonds
CHARMM residue (DLPE) has 96 bonds; AMBER residues ({'PE', 'LAL'}) have 62 bonds
CHARMM residue (DLPS) has 98 bonds; AMBER residues ({'LAL', 'PS'}) have 64 bonds
CHARMM residue (DLPA) has 87 bonds; AMBER residues ({'PH-', 'LAL'}) have 53 bonds
CHARMM residue (DLPG) has 98 bonds; AMBER residues ({'LAL', 'PGR'}) have 64 bonds
CHARMM residue (DMPC) has 117 bonds; AMBER residues ({'MY', 'PC'}) have 77 bonds
CHARMM residue (DMPE) has 108 bonds; AMBER residues ({'MY', 'PE'}) have 68 bonds
CHARMM residue (DMPS) has 110 bonds; AMBER residues ({'MY', 'PS'}) have 70 bonds
CHARMM residue (DMPA) has 99 bonds; AMBER residues ({'MY', 'PH-'}) have 59 bonds
CHARMM residue (DMPG) has 110 bonds; AMBER residues ({'MY', 'PGR'}) have 70 bonds
CHARMM residue (DPPC) has 129 bonds; AMBER residues ({'PC', 'PA'}) have 83 bonds
CHARMM residue (DPPE) has 120 bonds; AMBER residues ({'PE', 'PA'}) have 74 bonds
CHARMM residue (DPPS) has 122 bonds; AMBER residues ({'PS', 'PA'}) have 76 bonds
CHARMM residue (DPPA) has 111 bonds; AMBER residues ({'PH-', 'PA'}) have 65 bonds
CHARMM residue (DPPG) has 122 bonds; AMBER residues ({'PA', 'PGR'}) have 76 bonds
CHARMM residue (DSPC) has 141 bonds; AMBER residues ({'PC', 'ST'}) have 89 bonds
CHARMM residue (DSPE) has 132 bonds; AMBER residues ({'PE', 'ST'}) have 80 bonds
CHARMM residue (DSPS) has 134 bonds; AMBER residues ({'ST', 'PS'}) have 82 bonds
CHARMM residue (DSPA) has 123 bonds; AMBER residues ({'PH-', 'ST'}) have 71 bonds
CHARMM residue (DSPG) has 134 bonds; AMBER residues ({'ST', 'PGR'}) have 82 bonds
CHARMM residue (DOPC) has 137 bonds; AMBER residues ({'PC', 'OL'}) have 87 bonds
CHARMM residue (DOPE) has 128 bonds; AMBER residues ({'PE', 'OL'}) have 78 bonds
CHARMM residue (DOPS) has 130 bonds; AMBER residues ({'OL', 'PS'}) have 80 bonds
CHARMM residue (DOPA) has 119 bonds; AMBER residues ({'PH-', 'OL'}) have 69 bonds
CHARMM residue (DOPG) has 130 bonds; AMBER residues ({'OL', 'PGR'}) have 80 bonds
CHARMM residue (DAPC) has 137 bonds; AMBER residues ({'PC', 'AR'}) have 87 bonds
CHARMM residue (DAPE) has 128 bonds; AMBER residues ({'PE', 'AR'}) have 78 bonds
CHARMM residue (DAPS) has 130 bonds; AMBER residues ({'AR', 'PS'}) have 80 bonds
CHARMM residue (DAPA) has 119 bonds; AMBER residues ({'PH-', 'AR'}) have 69 bonds
CHARMM residue (DAPG) has 130 bonds; AMBER residues ({'AR', 'PGR'}) have 80 bonds
```
However, we're testing POPC, which is not among those that fail that test. 

I'm not sure if this is expected behavior by LEaP, but the PDB files converted from CHARMM to AMBER pile all the different AMBER residues into the same residue number:
```
HETATM   42  C12 PA  A   1      43.210   2.070  47.970  1.00  0.00           C
HETATM   43  H2R PA  A   1      42.510   1.210  47.920  1.00  0.00           H
HETATM   44  H2S PA  A   1      44.220   1.710  48.280  1.00  0.00           H
...
HETATM   26  HA  PC  A   1      39.740   6.410  51.040  1.00  0.00           H
HETATM   27  HB  PC  A   1      41.290   6.150  51.870  1.00  0.00           H
HETATM   28  C2  PC  A   1      41.310   5.780  49.750  1.00  0.00           C
...
HETATM   33  C12 OL  A   1      41.580   7.550  46.560  1.00  0.00           C
HETATM   34  H2R OL  A   1      41.880   8.620  46.520  1.00  0.00           H
HETATM   35  H2S OL  A   1      40.470   7.620  46.500  1.00  0.00           H
HETATM   45  C13 OL  A   1      42.130   6.740  45.380  1.00  0.00           C
...
```

**Comment by jchodera** [comment]
Crud. It looks like the missing atoms for non-POPC residues has to do with the fact that some CHARMM lipids can have multiple copies of the same AMBER residue type:
```
DLPC,0, C32 DLPC, C12 LAL ,True,106
DLPC,1, H2X DLPC, H2R LAL ,True,106
DLPC,2, H2Y DLPC, H2S LAL ,True,106
...
DLPC,46,H15C DLPC, H5C PC  ,True,106
DLPC,47, C12 DLPC, C32 PC  ,True,106
DLPC,48,H12A DLPC, H2A PC  ,True,106
...
DLPC,76, H3R DLPC, H3R LAL ,True,106
DLPC,77, H3S DLPC, H3S LAL ,True,106
DLPC,78, C24 DLPC, C14 LAL ,True,106
...
```

**Comment by peastman** [comment]
Why would that cause the number of bonds to be wrong?  All it does is clone the `<Residue>` tag from from the CHARMM file (which presumably has the right number of bonds), then copy over all the attributes of the `<Atom>` tags from the Amber file.

**Comment by jchodera** [comment]
It looks like the number of bonds is not the likely culprit here, since all the cases where the CHARMM residue is broken into three distinct residues match. 

> Why would that cause the number of bonds to be wrong? All it does is clone the <Residue> tag from from the CHARMM file (which presumably has the right number of bonds), then copy over all the attributes of the <Atom> tags from the Amber file.

Yes, I don't expect the number of connectivity of bonds is the culprit here.

The PDB file also looks to be properly converted. That leaves the bond parameters the likely remaining suspect.

**Comment by jchodera** [comment]
Nope, the parameters check with the original Amber `parm` file.

**Comment by peastman** [comment]
One other thing I thought of.  To create the Amber version, you're running the script that splits each residue into multiple residues, right?  And that script is presumably reordering the atoms.  Make sure you aren't loading the atom positions from one PDB file, then using them with a system that has a different ordering.

**Comment by jchodera** [comment]
> One other thing I thought of. To create the Amber version, you're running the script that splits each residue into multiple residues, right? 

Yes.

> And that script is presumably reordering the atoms. Make sure you aren't loading the atom positions from one PDB file, then using them with a system that has a different ordering.

I'm loading the AMBER version of the file through LEaP and the CHARMM version of the file through OpenMM.

**Comment by jchodera** [comment]
The code for the test is [here](https://github.com/choderalab/openmm-forcefields/pull/52/files#diff-60850f65ea5c62cdfb363b34095ee70aR1156).

**Comment by jchodera** [comment]
Oh, no, you're probably right about accidentally using the same set of coordinates! Stand by.

**Comment by jchodera** [comment]
OK, that was exactly it, @peastman. The lipid conversion/merging should be complete and lightly tested at this point.

**Pull request merged**
